project_id = "hwwwioyrsbewptuwvrix"

[functions.tcm-chat]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.send-followup-reminders]
verify_jwt = false

[functions.appointment-confirm]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.create-zoom-meeting]
verify_jwt = true
